float4 main
(
	float4 out_pos : WPOS,
	float4 out_col : COLOR,
	float2 out_tex : TEXCOORD0,
	uniform sampler2D tex,
	uniform float4 fog_state
) : COLOR
{
	// fog_state.rgb = fog colour
	// fog_state.a   = fog density
	float depth  = 1.0 / out_pos.w;
	float4 color = tex2D(tex, out_tex) * out_col;

	float factor = clamp(exp(fog_state.a * depth), 0.0, 1.0);
	color.rgb    = lerp(fog_state.rgb, color.rgb, factor);
	return color;
}
