TARGET		:= CCDOS
BUILD_DIR 	:= build/msdos
SOURCE_DIRS	:= src src/msdos

CFLAGS		=
LDFLAGS		= -g
LIBS		=
OEXT    	= .EXE
 # performance too slow if not in release mode
RELEASE		= 1

CC=i586-pc-msdosdjgpp-gcc


include misc/makefiles/Makefile_common.mk
