name: Upload binary
description: Uploads a compiled binary
inputs:
  SOURCE_FILE:
    description: 'Path to file to upload'
    required: true
    type: string
  DEST_NAME:
    description: 'Name to use for the uploaded artifact'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.DEST_NAME }}
        path: ${{ inputs.SOURCE_FILE }}
        if-no-files-found: error
