NAME		:= classicube
GAME_TITLE	:= ClassiCube

SOURCEDIRS	:= src
DEFINES		:= -DPLAT_NDS
LIBS		:= -ldswifi9 -lnds9
LIBDIRS		:= $(BLOCKSDS)/libs/dswifi $(BLOCKSDS)/libs/libnds

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
