// nvparse 1.0 output generated by NVIDIA Cg compiler
// cgc version 3.1.0013, build date Apr 24 2012
// command line args: -profile fp20
// source file: misc/xbox/ps_coloured.cg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile fp20
//program main
//var float4 input.color : $vin.COLOR : COLOR0 : 0 : 1
//var float4 main : $vout.COLOR : COLOR : -1 : 1
!!RC1.0
out.rgb = unsigned(col0.rgb);
out.a = unsigned(col0.a);
// 0 instructions
