// nvparse 1.0 output generated by NVIDIA Cg compiler
// cgc version 3.1.0013, build date Apr 24 2012
// command line args: -profile fp20
// source file: misc/xbox/ps_textured.cg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile fp20
//program main
//semantic main.tex
//var sampler2D tex :  :  0 : 1 : 1
//var float4 input.color : $vin.COLOR : COLOR0 : 0 : 1
//var float2 input.tex0 : $vin.TEXCOORD0 : TEXCOORD0 : 0 : 1
//var float4 main : $vout.COLOR : COLOR : -1 : 1
!!TS1.0
texture_2d();
// End of program
!!RC1.0
{
  rgb
  {
    col0 = tex0.rgb * col0.rgb;
  }
  alpha
  {
    col0 = tex0.a * col0.a;
  }
}
out.rgb = unsigned(col0.rgb);
out.a = unsigned(col0.a);
// 3 instructions
