void main(
	float4 in_pos : POSITION,
	float4 in_col : DIFFUSE,
	float4 in_tex : TEXCOORD,
	uniform float4x4 mvp,
	uniform float4   tex_offset,
	out float4 out_pos : HPOS,
	out float  out_fog : FOGC,
	out float4 out_col : COL0,
	out float4 out_tex : TEX0)
{
	float4 position;

	position = float4(in_pos.xyz, 1.0f);
	position = mul(position, mvp);
	position.xyz = position.xyz / position.w;
	
	out_pos = position;
	out_fog = position.w;
	out_col = in_col;
	out_tex = in_tex + tex_offset;
}
