// ClassicalSharp copyright 2014-2016 UnknownShadow200 | Licensed under MIT
using System;

namespace ClassicalSharp {
	
	/// <summary> Enumeration of all blocks in Minecraft Classic, including CPE ones. </summary>
	public enum Block : byte {
		Air = 0,
		Stone = 1,
		Grass = 2,
		Dirt = 3,
		Cobblestone = 4,
		WoodenPlanks = 5,
		Sapling = 6,
		Bedrock = 7,
		Water = 8,
		StillWater = 9,
		Lava = 10,
		StillLava = 11,
		Sand = 12,
		Gravel = 13,
		GoldOre = 14,
		IronOre = 15,
		CoalOre = 16,
		Wood = 17,
		Leaves = 18,
		Sponge = 19,
		Glass = 20,
		RedCloth = 21,
		OrangeCloth = 22,
		YellowCloth = 23,
		LimeCloth = 24,
		GreenCloth = 25,
		AquaCloth = 26,
		CyanCloth = 27,
		BlueCloth = 28,
		PurpleCloth = 29,
		IndigoCloth = 30,
		VioletCloth = 31,
		MagentaCloth = 32,
		PinkCloth = 33,
		BlackCloth = 34,
		GrayCloth = 35,
		WhiteCloth = 36,
		Dandelion = 37,
		Rose = 38,
		BrownMushroom = 39,
		RedMushroom = 40,
		GoldBlock = 41,
		IronBlock = 42,
		DoubleSlab = 43,
		Slab = 44,
		Brick = 45,
		TNT = 46,
		Bookshelf = 47,
		MossyCobblestone = 48,
		Obsidian = 49,
		
		CobblestoneSlab = 50,
		Rope = 51,
		Sandstone = 52,
		Snow = 53,
		Fire = 54,
		LightPinkWool = 55,
		ForestGreenWool = 56,
		BrownWool = 57,
		DeepBlueWool = 58,
		TurquoiseWool = 59,
		Ice = 60,
		CeramicTile = 61,
		Magma = 62,
		Pillar = 63,
		Crate = 64,
		StoneBrick = 65,
	}
}