CC=gcc
LIBS=-mwindows -lws2_32 -lwininet -lwinmm -limagehlp -ld3d9 -lcrypt32
CFLAGS=-g -w -pipe
SOURCES=$(wildcard *.c)
OBJECTS=$(patsubst %.c, %.o, $(SOURCES))
COMMITSHA=$(shell getsha)

EXECUTABLE=ClassiCube

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS)

$(OBJECTS): %.o : %.c
	$(CC) $(CFLAGS) -DCC_COMMIT_SHA=\"$(COMMITSHA)\" -c $< $(LIBS) -o $@

clean:
	rm -f $(EXECUTABLE) $(OBJECTS)
