name: Build latest (macOS 64 bit)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
      - AngledLighting
  workflow_dispatch:


concurrency:
  group: ${{ github.ref }}-mac64
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v5
      - name: Compile 64 bit macOS builds
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          COMMON_CFLAGS="-fno-stack-protector $LATEST_FLAG"
          COMMON_LDFLAGS="-s"

          make darwin RELEASE=1 TARGET=cc-mac64-gl1-x64 \
                EXTRA_CFLAGS="$COMMON_CFLAGS -arch x86_64 -mmacosx-version-min=10.5" \
                EXTRA_LDFLAGS="$COMMON_LDFLAGS -arch x86_64 -mmacosx-version-min=10.5"

          make darwin clean
          make darwin RELEASE=1 TARGET=cc-mac64-gl2-x64 \
                EXTRA_CFLAGS="$COMMON_CFLAGS -arch x86_64 -mmacosx-version-min=10.5 -DCC_GFX_BACKEND=CC_GFX_BACKEND_GL2" \
                EXTRA_LDFLAGS="$COMMON_LDFLAGS -arch x86_64 -mmacosx-version-min=10.5"

          make darwin clean
          make darwin RELEASE=1 TARGET=cc-mac64-gl2-arm64 \
                EXTRA_CFLAGS="$COMMON_CFLAGS -arch arm64 -DCC_GFX_BACKEND=CC_GFX_BACKEND_GL2" \
                EXTRA_LDFLAGS="$COMMON_LDFLAGS -arch arm64"
          # https://wiki.freepascal.org/Code_Signing_for_macOS#Ad_hoc_signing

      - name: Generate combined Intel + ARM64 build
        shell: bash
        run: |
          lipo -create -output cc-mac64-gl2 cc-mac64-gl2-x64 cc-mac64-gl2-arm64
          cp cc-mac64-gl1-x64 cc-mac64-gl1         
   
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-mac64-gl1'
          DEST_NAME: 'ClassiCube-mac64-OpenGL'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-mac64-gl2'
          DEST_NAME: 'ClassiCube-mac64-ModernGL'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-mac64-gl2-arm64'
          DEST_NAME: 'ClassiCube-mac-ARM64'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'mac64'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 64 bit macOS builds'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
