name: Build latest (Webclient)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-webclient
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: trzeci/emscripten-fastcomp:1.39.0
    steps:
      - uses: actions/checkout@v5
      - name: Compiles webclient
        run: |
          make web dist LEGACY=1

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'build/web/dist/ClassiCube.js'
          DEST_NAME: 'ClassiCube.js'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'webclient'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Webclient'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
