name: Build latest (Haiku)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-haiku
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: haiku/cross-compiler:x86_64-r1beta4
    steps:
      - uses: actions/checkout@v5

      - name: Compile haiku build
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          COMMON_CFLAGS="-fno-stack-protector $LATEST_FLAG"
          COMMON_LDFLAGS="-s"

          make haiku dist RELEASE=1 TARGET=cc-haiku64 CC=x86_64-unknown-haiku-gcc CXX=x86_64-unknown-haiku-g++ \
                EXTRA_CFLAGS="$COMMON_CFLAGS" \
                EXTRA_LDFLAGS="$COMMON_LDFLAGS"
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-haiku64'
          DEST_NAME: 'ClassiCube-haiku'


      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-haiku64.tar.gz'
          DEST_NAME: 'ClassiCube-haiku64.tar.gz'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'haiku'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Haiku build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
