name: Build latest (WinCE)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-wince
  cancel-in-progress: true

jobs:
# ===========================================
# =============== i386 WINCE ================
# ===========================================
  build-i386:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/enlyze/windows-ce-build-environment-i386:main-64dda99
    steps:
      - uses: actions/checkout@v5
      - name: Install prerequisites
        run: |
          apt install -y curl

      - name: Compile i386 WinCE builds
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          make wince RELEASE=1 TARGET=CC-i386 WINCE_ARCH=i386 \
                EXTRA_CFLAGS="$LATEST_FLAG"
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'CC-i386.exe'
          DEST_NAME: 'ClassiCube-i386.exe'
          
          
      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce i386 WinCE build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
# ===========================================
# ================ ARM WINCE ================
# ===========================================
  build-arm:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/enlyze/windows-ce-build-environment-arm:main-64dda99
    steps:
      - uses: actions/checkout@v5
      - name: Install prerequisites
        run: |
          apt install -y curl

      - name: Compile ARM WinCE builds
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          make wince RELEASE=1 TARGET=CC-arm WINCE_ARCH=armv4 \
                EXTRA_CFLAGS="$LATEST_FLAG"
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'CC-arm.exe'
          DEST_NAME: 'ClassiCube-arm.exe'
          
          
      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ARM WinCE build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
