name: Build latest (Haiku)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-haiku
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: haiku/cross-compiler:x86_64-r1beta4
    steps:
      - uses: actions/checkout@v5

      - name: Compile haiku build
        run: |
          make haiku RELEASE=1 TARGET=ClassiCube-haiku CC=x86_64-unknown-haiku-gcc EXTRA_CFLAGS=-fno-stack-protector
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-haiku'
          DEST_NAME: 'ClassiCube-haiku'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'haiku'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Haiku build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
