name: Build latest (Windows ARM32/64)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-windows-arm
  cancel-in-progress: true

jobs:
#============================================
# ============== ARM32 WINDOWS ==============
# ===========================================
  build-32:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-armv7
    steps:
      - uses: actions/checkout@v5
      - name: Compile ARM32 Windows builds
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          export EXTRA_CFLAGS="-fno-stack-protector -Wno-pragma-pack -DCC_NOMAIN -DCC_GFX_BACKEND=CC_GFX_BACKEND_D3D11"
          export EXTRA_LDFLAGS="-s -nostartfiles -Wl,-emain_real"

          make mingw RELEASE=1 TARGET=cc-arm32-d3d11.exe CC=armv7-w64-mingw32-gcc
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-arm32-d3d11.exe'
          DEST_NAME: 'ClassiCube-arm32-Direct3D11.exe'
          
          
      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 32 bit Windows-ARM build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
#============================================
# ============== ARM64 WINDOWS ==============
# ===========================================
  build-64:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-arm64
    steps:
      - uses: actions/checkout@v5
      - name: Compile ARM64 Windows builds
        shell: bash
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\\\"${GITHUB_SHA::9}\\\"

          export EXTRA_CFLAGS="-fno-stack-protector -Wno-pragma-pack -DCC_NOMAIN -DCC_GFX_BACKEND=CC_GFX_BACKEND_D3D11"
          export EXTRA_LDFLAGS="-s -nostartfiles -Wl,-emain_real"

          make mingw RELEASE=1 TARGET=cc-arm64-d3d11.exe CC=aarch64-w64-mingw32-gcc
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-arm64-d3d11.exe'
          DEST_NAME: 'ClassiCube-arm64-Direct3D11.exe'          
          

      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 64 bit Windows-ARM build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
